# Docker Compose Configuration
# visit https://docs.docker.com/compose/

version: '3.9'
services:

  # server container
  server:
    container_name: server-container
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: ${SERVER_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASS: ${DATABASE_PASS}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

